### ISSUE TITLE
[Feat] : 파일 검색 기능 관련 변경된 사항, 파일명을 통한 검색 기능만 생각

### ISSUE THREAD

**Issue by khyojun** [aws-cloud-clubs/ACC-MDT#11]
## :wrench:어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

이전에 진행하였던 #5 에 이어서 변경, 추가된 기능을 구현한다.

## :memo:작업 상세 내용

- [x] 새롭게 정의된 table 사용
- [x] scan 방식이 아닌 query 방식으로 파일명을 기반한 검색 진행!
- [x] scan 방식 query 방식 속도 비교

**Comment by Yeon-chae** [comment]
https://www.notion.so/7-30-2300-0100-7e9b676da92d492a8f519ac749ee6395?d=1268bc91af084ad892e5a4f1c32b0655&pvs=4#9dc263e3d9de400aa73f6de50d2e1379
한번 확인 하고 작업 부탁드립니다!
file_name(pk), user_id(sk),,

**Comment by khyojun** [comment]
> https://www.notion.so/7-30-2300-0100-7e9b676da92d492a8f519ac749ee6395?d=1268bc91af084ad892e5a4f1c32b0655&pvs=4#9dc263e3d9de400aa73f6de50d2e1379 한번 확인 하고 작업 부탁드립니다! file_name(pk), user_id(sk),,

네넵! 확인하였습니다! ㅠㅠ 죄송합니다! 착각해서 올렸나보네요!


![image](https://github.com/user-attachments/assets/44c3eca8-c2c3-46da-a781-e233154d66a6)


수정 작업 진행했습니다!
