### ISSUE TITLE
[Feat] : 패키지 기본 세팅 작업

### ISSUE THREAD

**Issue by khyojun** [aws-cloud-clubs/ACC-MDT#2]
## :wrench:어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

패키지 기본 세팅 작업을 진행합니다.

## :memo:작업 상세 내용

- [ ] 계층형으로 패키지 세팅(내부 dummy.txt를 활용해서 패키지가 반영되도록 진행)
   - controller
   - service
   - dto
   - repository
   - config

## :mega: 참고할만한 자료(선택)

https://nochoco-lee.tistory.com/56

**Comment by Yeon-chae** [comment]
이거 이슈가 안닫혀서 제가 직접 닫아둘게요!
